create table public.gastos (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  monto numeric not null
);

-- Habilitar seguridad (RLS)
alter table public.gastos enable row level security;

-- Política simple: Permitir todo a usuarios autenticados (ajustar según tus roles)
create policy "Usuarios pueden ver y crear gastos"
on public.gastos for all
to authenticated
using (true)
with check (true);